<?php
header('Content-Type: application/json');
include('../config.php');

$searchquery = "http://" . $yourip . "/searchquery";
$query = file_get_contents($searchquery);

$search = "http://" . $invidious . "/api/v1/search?q=" . $query;
$data = file_get_contents($search);

$result = json_decode($data);
?>
)]}'{"result": "ok", "timestamp": 1581239858, "build_signature": "en-GB:23727873,23874339", "content": {"actions": [{"action": 1}]}}]}, "length": {"runs": [{"text": "6:09"}], "item_type": "formatted_string", "accessibility": {"label": "6 minutes, 9 seconds"}}, "short_byline": {"runs": [{"text": "TheRichest"}], "item_type": "formatted_string"}, "title": {"runs": [{"text": "10 Of The Sexiest Criminals Ever"}], "item_type": "formatted_string"}, "view_count": {"runs": [{"text": "3,160,247 views"}], "item_type": "formatted_string"}, "item_type": "compact_video", "thumbnail_info": {"height": 136, "url": "http:\/\/i.ytimg.com\/vi\/JM6rC23yLn0\/hqdefault.jpg?w=240\u0026h=136\u0026sigh=eJYCrHPVs-CHaHo5IzZfEYNOTj8", "thumb_height": 136, "thumb_width": 240, "stitched": 0, "posx": 0, "posy": 0, "width": 240}, "endpoint": {"click_tracking_params": "CEkQpDAYCCITCJuoqLW4lMkCFc4bfgodIc8LMjIKZy1oaWdoLXJjaA==", "_navigation_endpoint_type": "generic_url", "url": "\/watch?v=JM6rC23yLn0"}, "upcoming_event_data": {"start_time": 0}, "encrypted_id": "JM6rC23yLn0", "is_watched": false, "badges": []}], "collapsed_item_count": 3, "collapsed_state_button_text": {"runs": [{"text": "+"}, {"text": "6"}, {"text": " more"}], "item_type": "formatted_string"}}, "thumbnail": {"url": "https:\/\/yt3.ggpht.com\/-Vo6fXInmjkI\/AAAAAAAAAAI\/AAAAAAAAAAA\/z6idR5VlfW4\/s88-c-k-no\/photo.jpg", "thumb_height": 88, "thumb_width": 88, "stitched": 0, "posx": 0, "posy": 19}, "title": {"runs": [{"text": "TheRichest"}], "item_type": "formatted_string"}, "item_type": "shelf", "endpoint": {"click_tracking_params": "CEYQ3BwYAyITCJuoqLW4lMkCFc4bfgodIc8LMg==", "_navigation_endpoint_type": "generic_url", "url": "\/channel\/UCdxi8d8qRsRyUi2ERYjYb-w"}, "badges": [], "subtitle": {"runs": [], "item_type": "formatted_string"}}], "continuations": []}, {"item_type": "item_section", "contents": [{"content": {"item_type": "vertical_list", "expanded_state_button_text": {"runs": [{"text": "Show all"}], "item_type": "formatted_string"}, "items": [{"menu": {"items": [{"item_type": "menu_service_item", "text": {"runs": [{"text": "Add to "}, {"text": "Watch Later"}], "item_type": "formatted_string"}, "service_endpoint": {"click_tracking_params": "CEQQqTsiEwibqKi1uJTJAhXOG34KHSHPCzI=", "_service_endpoint_type": "playlist_edit", "url": "\/playlist_edit_service?action_add_video=1", "params": {"playlist_id": "WL", "video_id": "OUI6iM8iPOs", "session_token": "QUFFLUhqa3RFVF9PcWtnejB5SllyMkRwbmFRQzZDaWJWUXxBQ3Jtc0tuekdUdVNyMklaWXNOX1pxbFYyRWlLeDEtbW5xZGRUMHRCNjktX1ZlaDlRUnpscHpkUUZHQXNXMDZaRGppcEhXWFpSOVdOcDYtT21HeHE3U0pvV0ZFQThCbWhHLThmMmFqOEhGRUlhU0JuamVyQVlnUlo2a2c0dzluT0dQNTdMS0s0QTBKMHotU3Bxb2tRaDdPalFfa0s3V1RHRUE="}, "external_user_id": "", "signed_in_username": "", "build_id": 0}
